
tasks:
  hello: 
    run: |
      sleep 1

  test:
    run: |
      Write-Host "Hello World"
    shell: pwsh

  has_deps:
    run: |
      Write-Host "Hello Moon"
    needs:
      - hello
    shell: pwsh
  docker:
    uses: docker://ubuntu
    with:
      args: bash -c 'echo hello world && echo \"$PWD\" && ls -la'
  pwsh_mods:
    uses: pwsh-module
    with:
      packages: ["powershell-yaml"]
      scope: 'currentuser'
jobs:
  test:
    steps:
      - hello
      - test